# Basic Site Information
title: Si Yuan's Data Science Hub
author: Si Yuan
description: Exploring the intersection of data science, deep learning, and innovation.
theme: minima

# Website Customization
markdown: kramdown
highlighter: rouge

# Social Links
github_username: imysw
linkedin_username: si-yuan-wong-322b87216

# Navigation Bar Links
collections:
  posts:
    output: true
    permalink: /blog/:title/

# SEO and Appearance
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 5

# Theme Customization
minima:
  skin: solarized
  social_links:
    github: https://github.com/imysw
    linkedin: https://www.linkedin.com/in/si-yuan-wong-322b87216

# URL Settings
baseurl: "/mywebsite"
url: "https://imysw.github.io"
permalink: pretty
